# Generated by Django 3.0.3 on 2020-02-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_app', '0004_auto_20200225_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time_update',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
