# Generated by Django 3.0.3 on 2020-02-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_app', '0007_auto_20200225_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-time_create'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
